"""empty message

Revision ID: 3c356a4254ab
Revises: 
Create Date: 2021-12-11 17:48:53.819681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c356a4254ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=80), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.String(length=50), nullable=False),
    sa.Column('battery', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveyData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=80), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.String(length=50), nullable=False),
    sa.Column('tampered', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ownership',
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ownership')
    op.drop_table('user')
    op.drop_table('surveyData')
    op.drop_table('project')
    op.drop_table('data')
    # ### end Alembic commands ###
